import type { Item, Settings, Task, TaskSummary } from './types';

const DB = 'yitu-static';
const STORE = 'records';
const settingsKey = 'settings';
const tasksKey = 'tasks';
const blobs = new Map<string, string>();

const defaults: Settings = {
  geminiBaseUrl: 'https://api.aiday.top', geminiModel: 'gemini-3.8-flash(high)', geminiAuth: 'bearer', geminiAuthHeader: '', geminiKeySet: false,
  extraInstruction: '', imageBaseUrl: 'https://task-api-1-cn.65535.space', imageModel: 'grok-imagine-image-2.0', imageKeySet: false,
  size: 'auto', resolution: '2K', quality: '', downloadWidth: 0, downloadHeight: 0, checkModel: false,
  promptConcurrency: 2, imageConcurrency: 2, pollSeconds: 2, timeoutMinutes: 30, autoPrompt: false, autoGenerate: false,
};
function openDb(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const r = indexedDB.open(DB, 1); r.onupgradeneeded = () => r.result.createObjectStore(STORE); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); }); }
async function dbGet<T>(key: string): Promise<T | undefined> { const db = await openDb(); return new Promise((resolve, reject) => { const r = db.transaction(STORE).objectStore(STORE).get(key); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); }); }
async function dbPut(key: string, value: unknown) { const db = await openDb(); return new Promise<void>((resolve, reject) => { const r = db.transaction(STORE, 'readwrite').objectStore(STORE).put(value, key); r.onsuccess = () => resolve(); r.onerror = () => reject(r.error); }); }
async function dbDelete(key: string) { const db = await openDb(); return new Promise<void>((resolve, reject) => { const r = db.transaction(STORE, 'readwrite').objectStore(STORE).delete(key); r.onsuccess = () => resolve(); r.onerror = () => reject(r.error); }); }
const key = (taskId: string, itemId: string, kind: string) => `${taskId}:${itemId}:${kind}`;
async function fileUrl(taskId: string, itemId: string, kind: 'source' | 'result') { const blob = await dbGet<Blob>(key(taskId, itemId, kind)); if (!blob) return ''; const k = key(taskId, itemId, kind); if (!blobs.has(k)) blobs.set(k, URL.createObjectURL(blob)); return blobs.get(k)!; }
async function hydrate(task: Task) { for (const item of task.items) { item.sourceUrl = await fileUrl(task.id, item.id, 'source'); item.resultUrl = await fileUrl(task.id, item.id, 'result'); } return task; }
async function allTasks(): Promise<Task[]> { return (await dbGet<Task[]>(tasksKey)) || []; }
async function saveTasks(tasks: Task[]) { await dbPut(tasksKey, tasks); }
function publicSettings(value: Settings & { geminiKey?: string; imageKey?: string }): Settings { return { ...value, geminiKeySet: !!value.geminiKey, imageKeySet: !!value.imageKey } as Settings; }
async function getSettings(): Promise<Settings & { geminiKey?: string; imageKey?: string }> { return (await dbGet<Settings & { geminiKey?: string; imageKey?: string }>(settingsKey)) || { ...defaults, geminiKey: '', imageKey: '' }; }
function upstreamUrl(base: string, suffix: string) { const u = new URL(base); return `${u.origin}${u.pathname.replace(/\/$/, '').replace(/\/(v1beta|v1)$/, '')}${suffix}`; }
async function jsonFetch(url: string, init: RequestInit) { const r = await fetch(url, init); const body = await r.json().catch(() => null); if (!r.ok) throw new Error(body?.error?.message || body?.error_message || `接口返回 HTTP ${r.status}`); return body; }
async function gemini(image: Blob, system: string, prompt: string, json = false) { const s = await getSettings(); if (!s.geminiBaseUrl || !s.geminiModel || !s.geminiKey) throw new Error('请先在设置中填写 Gemini 地址、模型和密钥'); const headers: Record<string,string> = { 'Content-Type': 'application/json' }; const hn = s.geminiAuth === 'google' ? 'x-goog-api-key' : s.geminiAuth === 'custom' ? s.geminiAuthHeader : 'Authorization'; headers[hn] = s.geminiAuth === 'bearer' ? `Bearer ${s.geminiKey}` : s.geminiKey; const data = await new Promise<string>(resolve => { const r = new FileReader(); r.onload = () => resolve(String(r.result).split(',')[1]); r.readAsDataURL(image); }); const body = await jsonFetch(`${upstreamUrl(s.geminiBaseUrl, '/v1beta/models')}/${encodeURIComponent(s.geminiModel)}:generateContent`, { method: 'POST', headers, body: JSON.stringify({ systemInstruction: { parts: [{ text: system }] }, contents: [{ role: 'user', parts: [{ text: prompt }, { inlineData: { mimeType: image.type, data } }] }], ...(json ? { generationConfig: { responseMimeType: 'application/json' } } : {}) }) }); const text = body?.candidates?.[0]?.content?.parts?.map((p: {text?: string}) => p.text || '').join('\n').trim(); if (!text) throw new Error('Gemini 没有返回文字'); return text; }
function itemFor(file: File): Item { return { id: crypto.randomUUID(), name: file.name, relativePath: (file as File & {webkitRelativePath?: string}).webkitRelativePath || file.name, prompt: '', generatedPrompt: '', promptStatus: 'idle', imageStatus: 'idle', validationStatus: 'idle', validationReason: '', error: '', errorCode: '', retryAt: '', hasResult: false, version: '', sourceUrl: '', resultUrl: '' }; }
async function getTask(id: string) { const task = (await allTasks()).find(t => t.id === id); return task ? hydrate(task) : null; }
async function updateTask(task: Task) { const list = await allTasks(); const i = list.findIndex(t => t.id === task.id); if (i >= 0) list[i] = task; else list.unshift(task); await saveTasks(list); return hydrate(task); }
async function generatePrompt(task: Task, item: Item) { const s = await getSettings(); item.promptStatus = 'running'; item.error = ''; await updateTask(task); try { const blob = await dbGet<Blob>(key(task.id, item.id, 'source')); const text = await gemini(blob!, [`将图片中的英文文案翻译为${task.language}，最后给出"..."替换为"..."，分行，不用列表。`, s.extraInstruction].filter(Boolean).join('\n'), '请识别图片中的英文文案，并严格按照上述格式逐行输出翻译结果。不要解释，不要添加列表符号。'); item.prompt = item.generatedPrompt = text; item.promptStatus = 'done'; } catch (e) { item.promptStatus = 'failed'; item.error = e instanceof Error ? e.message : '生成失败'; } await updateTask(task); return task; }
async function generatePrompts(task: Task) { for (const item of task.items.filter(i => i.promptStatus !== 'done')) await generatePrompt(task, item); return task; }
async function generateImage(task: Task, item: Item) { const s = await getSettings(); if (!s.imageBaseUrl || !s.imageModel || !s.imageKey) throw new Error('请先填写图片生成接口、模型和 API Key'); const source = await dbGet<Blob>(key(task.id, item.id, 'source')); const reader = await new Promise<string>(resolve => { const r = new FileReader(); r.onload = () => resolve(String(r.result)); r.readAsDataURL(source!); }); const input: Record<string,unknown> = { prompt: item.prompt, image: reader, n: 1, response_format: 'url' }; if (s.size) input.size = s.size; if (s.resolution) input.resolution = s.resolution; if (s.quality) input.quality = s.quality; const h = { Authorization: `Bearer ${s.imageKey}`, 'Content-Type': 'application/json', 'Idempotency-Key': crypto.randomUUID() }; const created = await jsonFetch(upstreamUrl(s.imageBaseUrl, '/v1/tasks'), { method: 'POST', headers: h, body: JSON.stringify({ kind: 'image', model: s.imageModel, operation: 'generate', input }) }); const deadline = Date.now() + s.timeoutMinutes * 60000; let state: any; do { await new Promise(r => setTimeout(r, s.pollSeconds * 1000)); state = await jsonFetch(`${upstreamUrl(s.imageBaseUrl, '/v1/tasks')}/${encodeURIComponent(created.id)}`, { headers: { Authorization: `Bearer ${s.imageKey}` } }); if (state.status === 'failed') throw new Error(state.error_message || '图片生成失败'); } while (state.status !== 'done' && Date.now() < deadline); if (state.status !== 'done') throw new Error('等待图片生成超时'); let result: Blob; if (state.result_urls?.[0]) { const r = await fetch(state.result_urls[0]); if (!r.ok) throw new Error('结果图片下载失败'); result = await r.blob(); } else if (state.result?.data?.[0]?.b64_json) { const b = atob(state.result.data[0].b64_json); result = new Blob([Uint8Array.from(b, c => c.charCodeAt(0))], { type: 'image/png' }); } else throw new Error('图片任务完成但没有返回图片'); await dbPut(key(task.id, item.id, 'result'), result); item.hasResult = true; item.version = String(Date.now()); }
async function generateImages(task: Task) { for (const item of task.items.filter(i => i.promptStatus === 'done' && !i.hasResult)) { item.imageStatus = 'running'; item.error = ''; await updateTask(task); try { await generateImage(task, item); item.imageStatus = 'done'; } catch (e) { item.imageStatus = 'failed'; item.error = e instanceof Error ? e.message : '生成失败'; } await updateTask(task); } return task; }
async function generateImageForItem(task: Task, item: Item) { item.imageStatus = 'running'; item.error = ''; await updateTask(task); try { await generateImage(task, item); item.imageStatus = 'done'; } catch (e) { item.imageStatus = 'failed'; item.error = e instanceof Error ? e.message : '生成失败'; } return await updateTask(task); }

export const json = (method: string, body?: unknown): RequestInit => ({ method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body ?? {}) });

export async function request<T>(url: string, options: RequestInit = {}): Promise<T> {
  const method = options.method || 'GET'; const match = url.match(/^\/api\/tasks(?:\/([^/]+)(?:\/items\/([^/]+))?(.*))?$/);
  if (url === '/api/config' && method === 'GET') return publicSettings(await getSettings()) as T;
  if (url === '/api/config' && method === 'PUT') { const body = JSON.parse(String(options.body || '{}')); const old = await getSettings(); const next = { ...old, ...body, geminiKey: body.geminiKey || old.geminiKey, imageKey: body.imageKey || old.imageKey }; await dbPut(settingsKey, next); return publicSettings(next) as T; }
  if (url === '/api/tasks' && method === 'GET') { const ts = await allTasks(); return ts.map(t => ({ id:t.id, language:t.language, createdAt:t.createdAt, count:t.items.length, done:t.items.filter(i=>i.imageStatus==='done').length })) as T; }
  if (!match) throw new Error('未知请求'); const [, taskId, itemId, rest] = match;
  if (!itemId && !rest && method === 'POST') { const body = options.body as FormData; const language = String(body.get('language') || ''); const files = [...body.getAll('files')].filter((x): x is File => x instanceof File); const t: Task = { id: crypto.randomUUID(), language, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), busy: false, items: files.map(itemFor) }; for (const [i,f] of files.entries()) await dbPut(key(t.id, t.items[i].id, 'source'), f); await updateTask(t); return await hydrate(t) as T; }
  const task = await getTask(taskId); if (!task) throw new Error('任务不存在');
  if (rest === '' && method === 'GET') return await hydrate(task) as T;
  if (rest === '' && method === 'DELETE') { await saveTasks((await allTasks()).filter(t => t.id !== taskId)); return { ok:true } as T; }
  if (rest === '/prompts/generate' && method === 'POST') { const body = JSON.parse(String(options.body || '{}')); if (typeof body.language === 'string' && body.language.trim()) task.language = body.language.trim().slice(0, 80); if (!task.language.trim()) throw new Error('请输入目标语言后再生成提示词'); await updateTask(task); return await hydrate(await generatePrompts(task)) as T; }
  if (rest === '/images/generate' && method === 'POST') return await hydrate(await generateImages(task)) as T;
  if (rest === '/validate' && method === 'POST') return await hydrate(task) as T;
  if (itemId && rest === '' && method === 'DELETE') { task.items = task.items.filter(i => i.id !== itemId); await updateTask(task); return await hydrate(task) as T; }
  if (itemId && rest === '/prompt' && method === 'PATCH') { const item = task.items.find(i=>i.id===itemId)!; item.prompt = JSON.parse(String(options.body)).prompt; item.promptStatus='done'; await updateTask(task); return await hydrate(task) as T; }
  if (itemId && rest === '/prompt/regenerate' && method === 'POST') { const body = JSON.parse(String(options.body || '{}')); if (typeof body.language === 'string' && body.language.trim()) task.language = body.language.trim().slice(0, 80); if (!task.language.trim()) throw new Error('请输入目标语言后再生成提示词'); const item = task.items.find(i => i.id === itemId); if (!item) throw new Error('图片不存在'); await updateTask(task); return await hydrate(await generatePrompt(task, item)) as T; }
  if (itemId && rest === '/image/regenerate' && method === 'POST') { const item = task.items.find(i=>i.id===itemId); if (!item) throw new Error('图片不存在'); item.hasResult=false; return await hydrate(await generateImageForItem(task, item)) as T; }
  if (rest === '/items' && method === 'POST') { const body=options.body as FormData; const files=[...body.getAll('files')].filter((x):x is File=>x instanceof File); for(const f of files){const i=itemFor(f); task.items.push(i); await dbPut(key(task.id,i.id,'source'),f);} await updateTask(task); return await hydrate(task) as T; }
  throw new Error('未知请求');
}
export function imageUrl(taskId: string, itemId: string, kind: 'source'|'result'|'download', _version = '') { const itemKind = kind === 'source' ? 'source' : 'result'; return blobs.get(key(taskId,itemId,itemKind)) || ''; }
export async function hydrateTask(task: Task) { return hydrate(task); }
